name: Sync Repositories

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm install -g grunt-cli
    - run: grunt clean copy rollup
    - name: Pushes to requirements repo
      uses: ./.github/actions/sync-repo
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'dist'
        destination_repo: 'ahmadayubi/synctest'
        destination_folder: 'build'
        user_email: aayub041@uottawa.ca
        user_name: 'ahmadayubi'
        commit_msg: '[GHA] Update the build files.'
        destination_branch: main
